[package]
name = "ladaemon"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]

[dependencies]
docopt = "0.6.81"
emailaddress = "0.3.0"
hyper = "0.9.6"
iron = "0.3.0"
lettre = "0.5.1"
openssl = "0.7.13"
rand = "0.3.14"
redis = "0.5.3"
router = "0.1.1"
rustc-serialize = "0.3.19"
serde_json = "0.7.0"
time = "0.1.35"
url = "1.1.0"
urlencoded = "0.3.0"
