[package]
name = "portier_broker"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
build = "build.rs"
description = "Reference implementation of the Portier broker protocol"
repository = "https://github.com/portier/portier-broker"
license = "MIT/Apache-2.0"

[[bin]]
name = "portier-broker"

[build-dependencies]
serde_codegen = "0.8.0"

[dependencies]
docopt = "0.6.81"
emailaddress = "0.3.1"
env_logger = "0.3.4"
hyper = "0.9.10"
iron = "0.4.0"
lettre = "0.6.0"
log = "0.3.6"
mustache = "0.7.0"
openssl = "0.7.13"
rand = "0.3.14"
redis = "0.7.0"
router = "0.2.0"
rustc-serialize = "0.3.19"
serde = "0.8.0"
serde_json = "0.8.0"
time = "0.1.35"
url = "1.1.0"
urlencoded = "0.4.0"
