name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  toolchain-compat:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: '1.46.0'
        profile: minimal
        default: true

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-mintoolchain-${{ hashFiles('**/Cargo.lock') }}

    - name: Check
      run: cargo check --locked

  linux-build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
        - 6379:6379
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: rustfmt, clippy
        default: true

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: cargo build --locked

    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Linux binary (debug)
        path: target/debug/portier-broker

    - name: Test
      run: cargo test --locked

    - name: Clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Rustfmt
      run: cargo fmt -- --check

    - name: Install gettext
      run: sudo apt-get install gettext

    - name: Check translations
      run: |
        set -e
        ./msgfmt.sh
        if [ -n "$(git status -s)" ]; then
          echo "If this fails, the lang/*.mo files are out of date."
          echo "To fix this, run: ./msgfmt.sh"
          exit 1
        fi

    - name: E2E test deps
      run: cd tests/e2e/ && yarn --frozen-lockfile

    - name: E2E test Firefox
      run: cd tests/e2e/ && SELENIUM_BROWSER=firefox ./main.js

    - name: E2E test Chrome
      run: cd tests/e2e/ && SELENIUM_BROWSER=chrome ./main.js

    - name: E2E test Redis
      run: cd tests/e2e/ && TEST_STORE=redis TEST_KEY_MANAGER=rotating ./main.js

    - name: E2E test SQLite
      run: cd tests/e2e/ && TEST_STORE=sqlite TEST_KEY_MANAGER=rotating ./main.js

    - name: E2E test sendmail
      run: cd tests/e2e/ && TEST_MAILER=sendmail ./main.js

    - name: E2E test Postmark
      run: cd tests/e2e/ && TEST_MAILER=postmark ./main.js

    - name: E2E test Mailgun
      run: cd tests/e2e/ && TEST_MAILER=mailgun ./main.js

    - name: Deploy staging
      if: github.repository == 'portier/portier-broker' && github.ref == 'refs/heads/main'
      run: |
        curl -X POST \
          -H 'Authorization: token ${{ secrets.DEPLOY_PAT }}' \
          -H 'Accept: application/vnd.github.v3+json' \
          https://api.github.com/repos/portier/public-infra/actions/workflows/update_testing_broker.yml/dispatches \
          -d '{ "ref": "main" }'

  macos-build:
    runs-on: macos-latest
    steps:

    # Workaround for: https://github.com/actions/cache/issues/403
    - name: Install GNU tar
      run: |
        brew install gnu-tar
        echo PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        default: true

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: cargo build --locked

    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: MacOS binary (debug)
        path: target/debug/portier-broker

    - name: Test
      run: cargo test --locked

    - name: E2E test deps
      run: cd tests/e2e/ && yarn --frozen-lockfile

    - name: E2E test Safari
      run: cd tests/e2e/ && SELENIUM_BROWSER=safari ./main.js
      # TODO: fails sporadically
      continue-on-error: true

  windows-build:
    runs-on: windows-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        default: true

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: v1-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: cargo build --locked

    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Windows binary (debug)
        path: target/debug/portier-broker.exe

    - name: Test
      run: cargo test --locked
